-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 06:48:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(125) NOT NULL,
  `lastname` VARCHAR(125) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(125) NOT NULL,
  `password` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fichetechnique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fichetechnique` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fichetechnique` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vignette` VARCHAR(255) NOT NULL,
  `synopsis` LONGTEXT NOT NULL,
  `duree` TIME NOT NULL,
  `casting` VARCHAR(300) NULL,
  `direction` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`avis` ;

CREATE TABLE IF NOT EXISTS `mydb`.`avis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` LONGTEXT NULL,
  `star` INT NOT NULL,
  `user_id` INT NOT NULL,
  `fichetechnique_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avis_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_avis_fichetechnique1_idx` (`fichetechnique_id` ASC) VISIBLE,
  CONSTRAINT `fk_avis_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avis_fichetechnique1`
    FOREIGN KEY (`fichetechnique_id`)
    REFERENCES `mydb`.`fichetechnique` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
